apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-kibana
  labels:
    name: elasticsearch-kibana
spec:
  type: NodePort
  selector:
    name: elasticsearch-kibana
  ports:
  - name: elasticsearch-http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: elasticsearch-transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  - name: kibana
    port: 5601
    protocol: TCP
    targetPort: 5601
    nodePort: 30081
#该端口是访问Kubernetes集群的外部端口必须为30000-32767之间.
---


