apiVersion: v1
kind: ReplicationController
metadata:
    name: elasticsearch-kibana
    labels:
      name: elasticsearch-kibana
spec:
  replicas: 1
  selector:
     name: elasticsearch-kibana
  template:
     metadata:
       labels:
          name: elasticsearch-kibana
     spec:
      nodeSelector:
        node: 172.16.2.233
      volumes:
      - name: "elasticsearch-storage"
        hostPath:
          path: "/var/lib/docker/elk-data"
      containers:
      - name: elasticsearch
        image: elasticsearch:2.3
        volumeMounts:
        - name: "elasticsearch-storage"
          mountPath: "/usr/share/elasticsearch/data"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
      - name: kibana
        image: kibana:4.5
        ports:
        - containerPort: 5601
#     volumes:
#     - name: "elasticsearch-storage"
#       hostPath:
#         path: "/var/lib/docker/elk-data"
