server:
  port: 10020
shell:
  ssh:
    port: 33020
  auth:
    simple:
      user:
        name: vpclub
        password: vp01b#6
spring:
  data:
     mongodb:
       host: 172.16.5.33
       port: 27017
       database: admin
  dubbo:
    protocol:
      name: dubbo
      port: 23020
      accesslog: true

    registry:
      address: zookeeper://172.16.5.30:2181
      register: true
      subscribe: true
platform:
     domain: "http://172.16.46.4:7074/api/1.0"
     method:
        login: "/StoreServer/Store/VerifyAccount"