kind: "List"
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      project: "elasticsearch"
      version: "2.2.260"
      group: "io.fabric8.devops.apps"
    name: "es-data"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "10Gi"
    volumeName: "es-datas"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "gogs-data"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "10Gi"
    volumeName: "gogs-data"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "jenkins-storage"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "10Gi"
    volumeName: "jenkins-storage"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "jenkins-jobs"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "5Gi"
    volumeName: "jenkins-common"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "jenkins-mvn-local-repo"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "5Gi"
    volumeName: "jenkins-all"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "jenkins-workspace"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "5Gi"
    volumeName: "jenkins-workspace"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "nexus-storage"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "18Gi"
    volumeName: "nexus-storage"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "registry-storage"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "40Gi"
    volumeName: "registry-storage"

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: es-datas
    labels:
      provider: "fabric8"
      project: "elasticsearch"
      version: "2.2.260"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 30Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.238

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkins-storage
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.238

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nexus-storage
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.238

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: gogs-data
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.233

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: registry-storage
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.238

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkins-all
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.238

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkins-common
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.233

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkins-workspace
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /var/nfs
      server: 172.16.2.233
