apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-rc
  namespace: kube-system
  labels:
    app: nginx-ingress
spec:
  replicas: 1
  selector:
    app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
    spec:
      imagePullSecrets:
      - name: aliregistrykey
      containers:
      - image: hub.docker.vpclub.cn/vpclub/nginx-ingress:0.2
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 18080
          hostPort: 18080

