server:
  port: 10010
shell:
  ssh:
    port: 33010
  auth:
    simple:
      user:
        name: vpclub
        password: vp01b#6

spring:
  datasource:
    name: devdb
    url: jdbc:mysql://172.16.45.3:3306/vp_traffic_monetisation?useUnicode=true&characterEncoding=utf-8
  #    url: jdbc:mysql://localhost:3306/vp_traffic_monetisation?useUnicode=true&characterEncoding=utf-8
    username: root
    password: "mQO7NpV1ohNjA37/xSIsNCIlVY4woR+zuAyeD3dBPpwcUX75gsZbvJftqhtpESDvItn6MUlJwrAAsi5+65fySQ=="
  #     password: Biyu5YzU+6sxDRbmWEa3B2uUcImzDo0BuXjTlL505+/pTb+/0Oqd3ou1R6J8+9Fy3CYrM18nBDqf6wAaPgUGOg==
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # encrypt password
    filters: config
    connectionProperties: "config.decrypt=true"
  dubbo:
    protocol:
      name: dubbo
      port: 23010
      accesslog: true

    registry:
      address: zookeeper://172.16.45.3:2181
      register: true
      subscribe: true
  data:
    mongodb:
      host: 172.16.45.3
      port: 27017
      database: admin