apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
#  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 80
    targetPort: 5601 
#  - port: 5601
    protocol: TCP
#    targetPort: ui
  selector:
    k8s-app: kibana-logging
