apiVersion: v1
kind: Service
metadata:
  name: netisation-consumer-svc
  labels:
    app: netisation-consumer
spec:
  ports:
  - port: 80
    targetPort: 10020
    protocol: TCP
    name: http
  selector:
    app: netisation-consumer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: netisation-consumer-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netisation-consumer 
    spec:
      imagePullSecrets:
      - name: aliregistrykey
      containers:
      - name: vp-traffic-monetisation-consumer
        image: hub.docker.vpclub.cn/vpclub_containers/vp-traffic-monetisation-consumer:1.0.0
        ports:
        - containerPort: 10020
        env:
        - name: PROFILE
          value: test
#        volumeMounts:
#        - name: netisation-consumer-vol
#          mountPath: /app/logs
#      volumes:
#      - name: netisation-consumer-vol
#        hostPath:
#          path: /tmp/vp-traffic-monetisation-consumer/app/logs
