apiVersion: v1
kind: Service
metadata:
  name: trafficcon-svc
  labels:
    app: traffic-con
spec:
  ports:
  - port: 80
    targetPort: 10020
    protocol: TCP
    name: http
  selector:
    app: traffic-con
