apiVersion: v1
kind: Service
metadata:
  name: netisation-provider-svc
  labels:
    app: netisation-provider
spec:
  ports:
  - port: 80
    targetPort: 10010
    protocol: TCP
    name: http
  selector:
    app: netisation-provider
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: netisation-provider-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: netisation-provider 
    spec:
      imagePullSecrets:
      - name: aliregistrykey
      containers:
      - name: vp-traffic-monetisation-provider
        image: hub.docker.vpclub.cn/vpclub_containers/vp-traffic-monetisation-provider:1.0.0
        ports:
        - containerPort: 10010
        env:
        - name: PROFILE
          value: test
#        volumeMounts:
#        - name: netisation-provider-vol
#          mountPath: /app/logs
#      volumes:
#      - name: netisation-provider-vol
#        hostPath:
#          path: /tmp/vp-traffic-monetisation-provider/app/logs
