apiVersion: v1
kind: ReplicationController
metadata:
  name: traffic-provider
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: traffic
    spec:
      containers:
      - name: vp-traffic-monetisation-provider
        image: hub.docker.vpclub.cn/vpclub_containers/vp-traffic-monetisation-provider:1.0.0
        ports:
        - containerPort: 10010
#        - port: 10010
      imagePullSecrets:
      - name: aliregistrykey

